name: Release Tools
run-name: "release tools ${{ github.ref }}"
on:
 workflow_dispatch

jobs:
  release:
    name: Build Tools
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum
      - name: Go Build
        run: make release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          body_path: README.md
          draft: true
